DROP TABLE IF EXISTS pets,
breeds,
owners;

-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE pets (
    id serial PRIMARY KEY,
    petname character varying(255) NOT NULL,
    checkedin boolean NOT NULL,
    staytype character varying(255),
    species character varying(255) NOT NULL,
    breed character varying(255) NOT NULL,
    sex character varying(255) NOT NULL,
    altered character varying(255) NOT NULL,
    birthday timestamp with time zone NOT NULL,
    weight integer,
    physicaldesc character varying(255),
    ownerid integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);

-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE breeds (
    id serial PRIMARY KEY,
    species character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);

-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE owners (
    id serial PRIMARY KEY,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL
);